name: Bug report
description: Problems with the software
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your feedback!
        
        有关讨论、建议或者咨询的内容请去往[讨论区](https://github.com/yetone/openai-translator/discussions)。

        For suggestions or help, please consider using [Github Discussion](https://github.com/yetone/openai-translator/discussions) instead.
  - type: checkboxes
    attributes:
      label: Search before asking
      description: |
        辛苦提 Bug 前，检索一下[问题](https://github.com/yetone/openai-translator/issues?q=)列表是否已经存在类似问题。麻烦提供系统版本、录屏或者截图、复现步骤，有助于更好的解决问题。

        非 Bug 相关，烦请移步[讨论区](https://github.com/yetone/openai-translator/discussions)找寻有关讨论。

        Please search [issues](https://github.com/yetone/openai-translator/issues) to check if your issue has already been reported.
      options:
        - label: >
            I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.
          required: true
  - type: textarea
    attributes:
      label: OpenAI Translator version
      description: >
        Please provide the version of OpenAI Translator you are using. If you are using the main branch, please provide the commit id.
    validations:
      required: true
  - type: textarea
    attributes:
      label: System version
      description: >
        Please provide the version of System you are using. If not applicable, please fill in `n/a`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Browser version
      description: >
        Please provide the version of Browser you are using. If not applicable, please fill in `n/a`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproduce step
      description: Please try to give reproducing steps to facilitate quick location of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you see instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We look forward to the community of developers or users helping solve OpenAI Translator problems together. If you are willing to submit a PR to fix this problem, please check the box.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"